--1. Display the number of states present in the LocationTable. 
--SELECT * FROM dbo.[Location];
SELECT COUNT(DISTINCT [State]) AS NoOfStates FROM dbo.[Location];
GO

--2. How many products are of regular type?
--SELECT * FROM dbo.Product
SELECT COUNT(*) AS ProdCount FROM dbo.Product WHERE [Type] = 'Regular';
GO

--3. How much spending has been done on marketing of product ID 1?
--SELECT * FROM dbo.[Fact]
SELECT SUM(Marketing) AS TotMarketingCost FROM dbo.Fact WHERE ProductId = 1;
GO

--4. What is the minimum sales of a product?
SELECT MIN(Sales) AS MinSales FROM dbo.Fact ;
GO
SELECT TOP 1 p.Product, MIN(f.Sales) as MinSales 
  FROM dbo.Product p INNER JOIN dbo.Fact f
    ON p.ProductId = f.ProductId
GROUP BY p.Product
ORDER BY MinSales;
GO
BEGIN
    DECLARE @ProdId smallint = 1

	SELECT p.Product, MIN(f.Sales) as MinSales 
	  FROM dbo.Product p INNER JOIN dbo.Fact f
		ON p.ProductId = f.ProductId
	  WHERE p.ProductId = @ProdId
	GROUP BY p.Product
	ORDER BY MinSales
END;
GO
--5. Display the max Cost of Good Sold (COGS). 
SELECT MAX(COGS) AS MaxCOGS FROM dbo.fact 
GO
--6. Display the details of the product where product type is coffee.
SELECT * FROM dbo.Product WHERE Product_Type = 'Coffee'
GO

--7. Display the details where total expenses are greater than 40. 
SELECT * FROM dbo.fact WHERE Total_Expenses > 40
GO

--8. What is the average sales in area code 719?
SELECT AVG(Sales) FROM dbo.fact WHERE Area_Code = 719
GO

--9. Find out the total profit generated by Colorado state.
SELECT SUM(Profit) AS TotProfit
  FROM dbo.fact f INNER JOIN dbo.[Location] l
    ON f.Area_Code = l.Area_Code
 WHERE l.[State] = 'Colorado'
 GO

--10. Display the average inventory for each product ID.
SELECT p.ProductId, AVG(f.Inventory) AS AvgInventory
 FROM dbo.Product p INNER JOIN dbo.fact f
   ON p.ProductId = f.ProductId
 GROUP BY p.ProductId

 GO

--11. Display state in a sequential order in a Location Table.
SELECT [State], Area_code,Market,Market_Size FROM dbo.Location
ORDER BY [State]
GO

SELECT DISTINCT[State] FROM dbo.Location
ORDER BY 1
GO

--12. Display the average budget of the Product where the average budget margin should be greater than 100. 
SELECT p.Product, AVG(f.Budget_Profit) AS AvgBudgetProfit
 FROM dbo.fact f INNER JOIN dbo.Product p
   ON f.ProductId = p.ProductId
GROUP BY p.Product
HAVING  AVG(f.Budget_Margin) > 100
GO

--13. What is the total sales done on date 2010-01-01?
SELECT SUM(f.Sales) AS TotalSales FROM dbo.fact f
WHERE f.[Date] = '2010-01-01'
GO

--14. Display the average total expense of each product ID on an individual date.
SELECT f.ProductId,f.[Date], AVG(f.Total_Expenses) AS AvgTotExpenses
  FROM dbo.fact f
GROUP BY f.ProductId, f.[Date]
ORDER BY 2
GO

--15. Display the table with the following attributes such as date, productID, product_type, product, sales, profit, state, area_code.
SELECT f.[Date], p.productID, p.Product_Type, p.Product, f.Sales, f.Profit, 
       l.[State], l.Area_Code
FROM dbo.fact f INNER JOIN dbo.Product p
  ON f.ProductId = p.ProductId
  INNER JOIN dbo.Location l
  ON l.Area_Code = f.Area_Code

--16. Display the rank without any gap to show the sales wise rank. 
SELECT
     DENSE_RANK() OVER(ORDER BY f.Sales DESC) AS sales_rank,
	 f.*
FROM dbo.fact f
GO


--17. Find the state wise profit and sales.
SELECT 
     l.[State],
	 SUM(f.Profit) AS TotProfit,
	 SUM(f.Sales) AS TotSales
FROM dbo.fact f INNER JOIN dbo.[Location] l
  ON f.Area_Code = l.Area_Code
GROUP BY l.State

--18. Find the state wise profit and sales along with the productname.
SELECT 
     l.[State],
	 p.Product,
	 SUM(f.Profit) AS TotProfit,
	 SUM(f.Sales) AS TotSales
FROM dbo.fact f INNER JOIN dbo.[Location] l
  ON f.Area_Code = l.Area_Code
INNER JOIN dbo.Product p
  ON p.ProductId = f.ProductId
GROUP BY l.State, p.Product
ORDER BY 1,2 

--19. If there is an increase in sales of 5%, calculate the increasedsales. 
SELECT 
	 f.Sales,
	 (f.Sales + f.Sales * 0.05) AS IncreasedSales,
	 f.*
FROM dbo.fact f
GO

--20. Find the maximum profit along with the product ID and producttype. 


--21. Create a stored procedure to fetch the result according to the product type from Product Table.
--22. Write a query by creating a condition in which if the total expenses is less than 60 then it is a profit or else loss. 
--23. Give the total weekly sales value with the date and product ID details. Use roll-up to pull the data in hierarchical order. 
--24. Apply union and intersection operator on the tables which consist of attribute area code. 
--25. Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference. 
--26. Change the product type from coffee to tea where product ID is 1 and undo it. 
--27. Display the date, product ID and sales where total expenses are between 100 to 200. 
--28. Delete the records in the Product Table for regular type. 
--29. Display the ASCII value of the fifth character from the columnProduct